POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name" : "Category 3",
  "description" : "Category 3 description"
}

###
GET http://localhost:8080/category HTTP/1.1

###
GET http://localhost:8080/category/653c7d53-38df-46bf-ae1a-b21fa3d8a273 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Product 2",
  "description" : "Product description",
  "price": 200,
  "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "category_id": "653c7d53-38df-46bf-ae1a-b21fa3d8a273"
}

###
GET http://localhost:8080/product/8f7d38cf-b1ab-46d6-90cc-dde73267464f HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/product/category/653c7d53-38df-46bf-ae1a-b21fa3d8a273 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json